name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  root:
    name: Deploy root
    runs-on: ubuntu-latest
    steps:
      - name: decrypt
        env:
          root_rsa: ${{ secrets.root_rsa }}
        run: |
          mkdir ~/.ssh && chmod 700 ~/.ssh
          echo "$root_rsa" > ~/.ssh/root_rsa
          chmod 600 ~/.ssh/root_rsa
          cat <<EOF > ~/.ssh/config
          Host arhythmetic.github.io
              HostName github.com
              Port 22
              User git
              IdentityFile ~/.ssh/root_rsa
          EOF
          chmod 644 ~/.ssh/config

      - name: clone
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: config
        run: |
          export TZ=Asia/Shanghai
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global core.quotepath off

      - name: status
        run: git status

      - name: pull
        run: |
          git remote add root git@arhythmetic.github.io:Arhythmetic/arhythmetic.github.io.git
          git subtree add --prefix=root/public/ root master --squash

      - name: generate
        run: |
          cd root
          rm -rf public/ && cp -r source/ public/
          cd ..

      - name: push
        run: |
          git add -f root/public/
          git commit --allow-empty -m "Deployed by GitHub Actions"
          git subtree split --prefix=root/public/ --branch root
          git subtree push --prefix=root/public/ root master --squash

  zh:
    name: Deploy zh
    runs-on: ubuntu-latest
    steps:
      - name: decrypt
        env:
          zh_rsa: ${{ secrets.zh_rsa }}
        run: |
          mkdir ~/.ssh && chmod 700 ~/.ssh
          echo "$zh_rsa" > ~/.ssh/zh_rsa
          chmod 600 ~/.ssh/zh_rsa
          cat <<EOF > ~/.ssh/config
          Host zh.arhythmetic.github.io
              HostName github.com
              Port 22
              User git
              IdentityFile ~/.ssh/zh_rsa
          EOF
          chmod 644 ~/.ssh/config

      - name: clone
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install
        run: |
          npm install -g npm@latest
          npm install -g hexo-cli

      - name: config
        run: |
          export TZ=Asia/Shanghai
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global core.quotepath off

      - name: status
        run: git status

      - name: pull
        run: |
          git remote add zh git@zh.arhythmetic.github.io:Arhythmetic/zh.git
          git subtree add --prefix=zh/public/ zh master --squash

      - name: generate
        run: |
          cd zh
          npm install && npm update && npm audit fix
          hexo clean && hexo generate
          cd ..

      - name: push
        run: |
          git add zh/package.json zh/package-lock.json
          git add -f zh/public/
          git commit --allow-empty -m "Deployed by GitHub Actions"
          git subtree split --prefix=zh/public/ --branch zh
          git subtree push --prefix=zh/public/ zh master --squash

  en:
    name: Deploy en
    runs-on: ubuntu-latest
    steps:
      - name: decrypt
        env:
          en_rsa: ${{ secrets.en_rsa }}
        run: |
          mkdir ~/.ssh && chmod 700 ~/.ssh
          echo "$en_rsa" > ~/.ssh/en_rsa
          chmod 600 ~/.ssh/en_rsa
          cat <<EOF > ~/.ssh/config
          Host en.arhythmetic.github.io
              HostName github.com
              Port 22
              User git
              IdentityFile ~/.ssh/en_rsa
          EOF
          chmod 644 ~/.ssh/config

      - name: clone
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install
        run: |
          npm install -g npm@latest
          npm install -g hexo-cli

      - name: config
        run: |
          export TZ=Asia/Shanghai
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global core.quotepath off

      - name: status
        run: git status

      - name: pull
        run: |
          git remote add en git@en.arhythmetic.github.io:Arhythmetic/en.git
          git subtree add --prefix=en/public/ en master --squash

      - name: generate
        run: |
          cd en
          npm install && npm update && npm audit fix
          hexo clean && hexo generate
          cd ..

      - name: push
        run: |
          git add en/package.json en/package-lock.json
          git add -f en/public/
          git commit --allow-empty -m "Deployed by GitHub Actions"
          git subtree split --prefix=en/public/ --branch en
          git subtree push --prefix=en/public/ en master --squash
